language: cpp
matrix:
  include:
  - env: QT=qt5osx
    os: osx
  - env: QT=qt4
    os: linux
  - env: QT=qt5
    os: linux
    services: xvfb
  - env: QT=qt5NoPoppler
    os: linux
  - env: QT=qt5Release
    os: linux
  - env: QT=qt5win
    os: linux
    services: docker
dist: xenial
sudo: required
branches:
  only:
  - master
  - "/^\\d+.\\d+(.\\d+)?(\\S*)?$/"
before_install:
- "${TRAVIS_BUILD_DIR}/travis-ci/get-dependencies.sh"
before_script:
- export DISPLAY=:99.0
- "${TRAVIS_BUILD_DIR}/travis-ci/configure.sh"
script:
- if [ $QT = qt5win ]; then PATH=$PATH:/opt/mxe/usr/bin; fi
- make -j 2
- export QT_QPA_PLATFORM=minimal
- if [ $QT = qt5 ]; then ./texstudio --auto-tests; fi
after_success:
- "${TRAVIS_BUILD_DIR}/travis-ci/package.sh"
deploy: 
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: KgUMy4SOcpOZJhhjOedXXsZCsFRJ2utrhJxkEHaaMoPs6whlE4aoI1jV9/N1K6W3BKtLV3SkVN4mBAyBTEqRUv/Fd1Akv0arMCmA6+Q/v6sdsdmfyHzg+8uH17kZzHjP3txv4VK5bXZ9gApxsHK0N6bvbnG+Pn2E31+rN8xZT/02VKkwwO2kczz+CZgOMi1Ft2IP0LrP9Fdhm42ky5tS2LOn9ig9hJIq/QNRBv6LmTpTSit674wv5O8gAPJWP//rRfNxjro5Ee29nEUDNlQsKgrF/J5yikzsjUXC4k22cXIausWhiga/zXrzZzev5W+EPyXSMOs2R3MBQbq2wO84Q58LDfj/zUgihe2xnbKIiIbGd4zrpjtM5fitXiETjJcveyShED4F+6X8eBGlScvrx4dpFM8EKcRMPOWrr6cMEYhviscacBjon2kOOWwJdTpDnYdHWXGZAFuMVBsWpOMX7kOXEriN41c/zSKNICQMHoy7k2sTEtF+zQybf0RdIbqQR0IqyshnFh1p3CqnBoOg2G0mDsFGey5Ayug2Wd6tqcOUstqdYs5LpNi0JxurogZQyoUWdmjP72fXZgGw1F0AqmjRCRzSnzY8m8D5CkkB9DVZ7FWOQucksomtUeKLODBpoM4IFi74BdnIE5dlqOe79bOwUXICCYqYpNfDU6Qde14=
    file: 
      - "${TRAVIS_BUILD_DIR}/texstudio-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.dmg"
    on:
      tags: true 
      condition: -f "${TRAVIS_BUILD_DIR}/texstudio-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.dmg"
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: KgUMy4SOcpOZJhhjOedXXsZCsFRJ2utrhJxkEHaaMoPs6whlE4aoI1jV9/N1K6W3BKtLV3SkVN4mBAyBTEqRUv/Fd1Akv0arMCmA6+Q/v6sdsdmfyHzg+8uH17kZzHjP3txv4VK5bXZ9gApxsHK0N6bvbnG+Pn2E31+rN8xZT/02VKkwwO2kczz+CZgOMi1Ft2IP0LrP9Fdhm42ky5tS2LOn9ig9hJIq/QNRBv6LmTpTSit674wv5O8gAPJWP//rRfNxjro5Ee29nEUDNlQsKgrF/J5yikzsjUXC4k22cXIausWhiga/zXrzZzev5W+EPyXSMOs2R3MBQbq2wO84Q58LDfj/zUgihe2xnbKIiIbGd4zrpjtM5fitXiETjJcveyShED4F+6X8eBGlScvrx4dpFM8EKcRMPOWrr6cMEYhviscacBjon2kOOWwJdTpDnYdHWXGZAFuMVBsWpOMX7kOXEriN41c/zSKNICQMHoy7k2sTEtF+zQybf0RdIbqQR0IqyshnFh1p3CqnBoOg2G0mDsFGey5Ayug2Wd6tqcOUstqdYs5LpNi0JxurogZQyoUWdmjP72fXZgGw1F0AqmjRCRzSnzY8m8D5CkkB9DVZ7FWOQucksomtUeKLODBpoM4IFi74BdnIE5dlqOe79bOwUXICCYqYpNfDU6Qde14=
    file: 
      - "${TRAVIS_BUILD_DIR}/texstudio-${TRAVIS_TAG}-win-portable-qt5.zip"
    on:
      tags: true 
      condition: -f "${TRAVIS_BUILD_DIR}/texstudio-${TRAVIS_TAG}-win-portable-qt5.zip"
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: KgUMy4SOcpOZJhhjOedXXsZCsFRJ2utrhJxkEHaaMoPs6whlE4aoI1jV9/N1K6W3BKtLV3SkVN4mBAyBTEqRUv/Fd1Akv0arMCmA6+Q/v6sdsdmfyHzg+8uH17kZzHjP3txv4VK5bXZ9gApxsHK0N6bvbnG+Pn2E31+rN8xZT/02VKkwwO2kczz+CZgOMi1Ft2IP0LrP9Fdhm42ky5tS2LOn9ig9hJIq/QNRBv6LmTpTSit674wv5O8gAPJWP//rRfNxjro5Ee29nEUDNlQsKgrF/J5yikzsjUXC4k22cXIausWhiga/zXrzZzev5W+EPyXSMOs2R3MBQbq2wO84Q58LDfj/zUgihe2xnbKIiIbGd4zrpjtM5fitXiETjJcveyShED4F+6X8eBGlScvrx4dpFM8EKcRMPOWrr6cMEYhviscacBjon2kOOWwJdTpDnYdHWXGZAFuMVBsWpOMX7kOXEriN41c/zSKNICQMHoy7k2sTEtF+zQybf0RdIbqQR0IqyshnFh1p3CqnBoOg2G0mDsFGey5Ayug2Wd6tqcOUstqdYs5LpNi0JxurogZQyoUWdmjP72fXZgGw1F0AqmjRCRzSnzY8m8D5CkkB9DVZ7FWOQucksomtUeKLODBpoM4IFi74BdnIE5dlqOe79bOwUXICCYqYpNfDU6Qde14=
    file: 
      - "${TRAVIS_BUILD_DIR}/texstudio-${TRAVIS_TAG}-win-qt5.exe"
    on:
      tags: true 
      condition: -f "${TRAVIS_BUILD_DIR}/texstudio-${TRAVIS_TAG}-win-qt5.exe"
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: KgUMy4SOcpOZJhhjOedXXsZCsFRJ2utrhJxkEHaaMoPs6whlE4aoI1jV9/N1K6W3BKtLV3SkVN4mBAyBTEqRUv/Fd1Akv0arMCmA6+Q/v6sdsdmfyHzg+8uH17kZzHjP3txv4VK5bXZ9gApxsHK0N6bvbnG+Pn2E31+rN8xZT/02VKkwwO2kczz+CZgOMi1Ft2IP0LrP9Fdhm42ky5tS2LOn9ig9hJIq/QNRBv6LmTpTSit674wv5O8gAPJWP//rRfNxjro5Ee29nEUDNlQsKgrF/J5yikzsjUXC4k22cXIausWhiga/zXrzZzev5W+EPyXSMOs2R3MBQbq2wO84Q58LDfj/zUgihe2xnbKIiIbGd4zrpjtM5fitXiETjJcveyShED4F+6X8eBGlScvrx4dpFM8EKcRMPOWrr6cMEYhviscacBjon2kOOWwJdTpDnYdHWXGZAFuMVBsWpOMX7kOXEriN41c/zSKNICQMHoy7k2sTEtF+zQybf0RdIbqQR0IqyshnFh1p3CqnBoOg2G0mDsFGey5Ayug2Wd6tqcOUstqdYs5LpNi0JxurogZQyoUWdmjP72fXZgGw1F0AqmjRCRzSnzY8m8D5CkkB9DVZ7FWOQucksomtUeKLODBpoM4IFi74BdnIE5dlqOe79bOwUXICCYqYpNfDU6Qde14=
    file: 
      - "${TRAVIS_BUILD_DIR}/texstudio-${TRAVIS_TAG}-x86_64.AppImage"
    on:
      tags: true 
      condition: -f "${TRAVIS_BUILD_DIR}/texstudio-${TRAVIS_TAG}-x86_64.AppImage"

